---
name: ∫ Integration

on:
  push:
    branches:
      - master

jobs:
  integrate:
    name: ∮ Integrate
    runs-on: ubuntu-latest
    steps:
      - name: 💳 Checking out
        uses: actions/checkout@v2
      - name: 🤠 Roundup
        uses: nutjob4life/roundup-action@maven
        with:
          assembly: unstable
        env:
          pypi_username: ${{secrets.PYPI_USERNAME}}
          pypi_password: ${{secrets.PYPI_PASSWORD}}
          ossrh_username: ${{secrets.OSSRH_USERNAME}}
          ossrh_password: ${{secrets.OSSRH_PASSWORD}}
          ADMIN_GITHUB_TOKEN: ${{secrets.PAT}}

...
